name: Push Docker Image to DockerHub

on:
  push:
    branches:
      - release

env:
  DOCKER_IMAGE: fedeberon/soccam-be
  MP_ACCESS_TOKEN: ${{ secrets.MP_ACCESS_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log environment context
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
          echo "Docker image: ${{ env.DOCKER_IMAGE }}"
          if [ -n "${MP_ACCESS_TOKEN:-}" ]; then
            echo "MP_ACCESS_TOKEN is present (hidden for security)."
          else
            echo "WARNING: MP_ACCESS_TOKEN is not set."
          fi

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: fedeberon
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          push: true
